#!/usr/bin/env bash

# exit the script if somewhere is an uninitialised variable
set -o nounset
#  exit the script if any statement returns a non-true value
set -o errexit

vivian_root=$(readlink -f $(dirname $0))
cd $vivian_root

source .env

current_date=$(date +%Y%m%d-%H%M)

source help.sh
source git.sh
source mysql.sh
source encryption.sh
source rsync.sh
source logging.sh
source misc.sh

repos_dir=$vivian_root/var/repos

for arg in "$@"; do
case "$arg" in
	--mysql-clean|mysql-clean)
		mysql_clean $repos_dir
	;;
	--mysql-encrypt|mysql-encrypt)
		mysql_encrypt $repos_dir
	;;
	--rsync|rsync)
		rsync_to_storages $repos_dir "${remote_storages[@]}"
	;;
	--restore-decrypt|restore-decrypt)
		restore_decrypt var/restore
	;;
	--files|files)
		backup_files files.conf $repos_dir/files
		encrypt_archives_in_dir $repos_dir
	;;
	--clear-logs|clear-logs)
		vivian_clear_logs
	;;
	*)
		show_help $arg
esac
done

if [[ -z "$1" ]]; then
	show_help
fi
