#!/usr/bin/env bash

program_root=$(readlink -f $(dirname $0))
cd $program_root

source core.sh
source .env
source encryption.sh

show_usage() {
	cat <<-USAGE
Usage: $0 <FILE OR DIRECTORY TO DECRYPT> [<ANOTHER FILE OR DIRECTORY TO DECRYPT>]...
USAGE
}

if [[ $# -eq 0 ]]; then
	show_usage
	exit 1
fi

for arg in "$@"; do
case "$arg" in
	--help|-h)
		show_usage
	;;
	*)
		decrypt_files "$arg"
esac
done
