#!/usr/bin/env bash

# exit the script if somewhere is an uninitialised variable
set -o nounset
#  exit the script if any statement returns a non-true value
set -o errexit

vivian_root=$(readlink -f $(dirname $0))
cd $vivian_root

source .env

current_date=$(date +%Y%m%d-%H%M)

# storage path
vivian_localbkp="${vivian_root}/localbkp"
# restore path
vivian_restore="${vivian_root}/restore"

source help.sh
source mysql.sh
source encryption.sh
source rsync.sh
source logging.sh
source misc.sh

for arg in "$@"; do
case "$arg" in
	--mysql-clean|mysql-clean)
		mysql_clean $vivian_localbkp
	;;
	--mysql-encrypt|mysql-encrypt)
		mysql_encrypt $vivian_localbkp
	;;
	--rsync|rsync)
		rsync_to_storages "${remote_storages[@]}"
	;;
	--restore-decrypt|restore-decrypt)
		restore_decrypt $vivian_restore
	;;
	--files|files)
		backup_files
	;;
	--clear-logs|clear-logs)
		vivian_clear_logs
	;;
	*)
		show_help $arg
esac
done

if [[ -z "$1" ]]; then
	show_help
fi
